"""for api 1

Revision ID: a1ca920e0570
Revises: 62416bc0c673
Create Date: 2019-12-07 20:54:47.031888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1ca920e0570'
down_revision = '62416bc0c673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('list', 'item')
    op.drop_column('list', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list', sa.Column('name', sa.VARCHAR(length=30), nullable=True))
    op.add_column('list', sa.Column('item', sa.VARCHAR(length=30), nullable=True))
    # ### end Alembic commands ###
